---
title: "Psilocybin Project 1"
subtitle: "Figures"
author: "Kennedi Todd"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: cerulean
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: inline
---

# Setup
## Working directory
```{r setup}
knitr::opts_knit$set(root.dir = ".")
```

## Libraries
```{r libraries, message=FALSE, warning=FALSE}
library(plotly) # plot_ly()
library(tidyr)  # pivot_longer()
library(ComplexUpset)
library(UpSetR)
```

## User defined variables
```{r set_variables}
out <- "../../results/all_samples_combat/"
out2 <- "all_samples_combat"
model <- "DEGs_with_hbb/both_sexes/"
treatment_order <- c("saline","psilocybin")
treatment_colors <- c("gray60","springgreen2")
sex_order <- c("M","F")
sex_colors <- c("gold2","purple")
group_order <- c("S.8h","S.24h","S.7d",
                 "L.8h","L.24h","L.7d",
                 "H.8h","H.24h","H.7d")
group_colors <- c("gray90","gray60","gray30","lightblue","cornflowerblue","blue",
                          "sienna1","red2","red4")
```

## Save functions
```{r save_functions}
saveToPDF <- function(...) {
    d = dev.copy(pdf,...)
    dev.off(d)
}
```

# Upset
## Low dose
```{r}
# set var
thresh <- 0.1
myLfc <- 0.2

# paths
prefix <- paste0(out, model, "DEG_tables/")
suffix <- "_FDRq_1.00_LFC_0.00.tsv"

# read tables
low.8h <- read.delim(paste0(out, model, 
                            "DEG_tables/L.8h_vs_S.8h_FDRq_1.00_LFC_0.00.tsv"))
low.24h <- read.delim(paste0(out, model, 
                             "DEG_tables/L.24h_vs_S.24h_FDRq_1.00_LFC_0.00.tsv"))
low.7d <- read.delim(paste0(out, model, 
                            "DEG_tables/L.7d_vs_S.7d_FDRq_1.00_LFC_0.00.tsv"))
rownames(low.8h) <- low.8h$gene_name_unique
rownames(low.24h) <- low.24h$gene_name_unique
rownames(low.7d) <- low.7d$gene_name_unique

# filter on pval
low.8h <- low.8h[low.8h$adj.P.Val < thresh,]
low.24h <- low.24h[low.24h$adj.P.Val < thresh,]
low.7d <- low.7d[low.7d$adj.P.Val < thresh,]

# Subset lists
low.8h.up <- subset(low.8h$gene_name_unique, low.8h$logFC > myLfc)
low.8h.down <- subset(low.8h$gene_name_unique, low.8h$logFC < -myLfc)
low.24h.up <- subset(low.24h$gene_name_unique, low.24h$logFC > myLfc)
low.24h.down <- subset(low.24h$gene_name_unique, low.24h$logFC < -myLfc)
low.7d.up <- subset(low.7d$gene_name_unique, low.7d$logFC > myLfc)
low.7d.down <- subset(low.7d$gene_name_unique, low.7d$logFC < -myLfc)
list_input <- list("7 day Low Dose Psilocybin vs Saline Up-regulated" = low.7d.up,
                   "24 hr Low Dose Psilocybin vs Saline Up-regulated" = low.24h.up,
                   "8 hr Low Dose Psilocybin vs Saline Up-regulated" = low.8h.up,
                   "7 day Low Dose Psilocybin vs Saline Down-regulated" = low.7d.down,
                   "24 hr Low Dose Psilocybin vs Saline Down-regulated" = low.24h.down,
                   "8 hr Low Dose Psilocybin vs Saline Down-regulated" = low.8h.down)
data <- fromList(list_input)
  
# store names
names <- colnames(data)
  
# plot
upset_gene <- ComplexUpset::upset(data, 
				  names,
				  set_sizes=(
					upset_set_size()
					+ geom_text(aes(label=..count..), hjust=1.1, stat='count')
					+ expand_limits(y=400)),
				  queries = list(upset_query("8 hr Low Dose Psilocybin vs Saline Up-regulated", fill = "red"),
								 upset_query("24 hr Low Dose Psilocybin vs Saline Up-regulated", fill = "red"),
								 upset_query("7 day Low Dose Psilocybin vs Saline Up-regulated", fill = "red"),
								 upset_query("8 hr Low Dose Psilocybin vs Saline Down-regulated", fill = "blue"),
								 upset_query("24 hr Low Dose Psilocybin vs Saline Down-regulated", fill = "blue"),
								 upset_query("7 day Low Dose Psilocybin vs Saline Down-regulated", fill = "blue")),
				  base_annotations = list('Intersection size' = (
					intersection_size(bar_number_threshold=1, width=0.5)
					+ scale_y_continuous(expand=expansion(mult=c(0, 0.05)),limits = c(0,250)) # space on top
					+ theme(
						  # hide grid lines
						  panel.grid.major=element_blank(),
						  panel.grid.minor=element_blank(),
						  # show axis lines
						  axis.line=element_line(colour='black')))),
				  stripes = upset_stripes(
					geom=geom_segment(size=12),  # make the stripes larger
					colors=c('grey95', 'white')),
				  # to prevent connectors from getting the colorured
				  # use `fill` instead of `color`, together with `shape='circle filled'`
				  matrix = intersection_matrix(
					geom=geom_point(
					  shape='circle filled',
					  size=3,
					  stroke=0.45)),
				  sort_sets=FALSE,
				  sort_intersections='descending'
				)

upset_gene <- upset_gene + ggtitle(paste0("L Comparison, FDRq < ", format(thresh, nsmall = 2),
                                          ", |LFC| > ", format(myLfc, nsmall = 2)))

# save
pdf(paste0(out, model, "/upset/L_comparison_FDRq_", format(thresh, nsmall = 2), 
           "_LFC_", format(myLfc, nsmall = 2), ".pdf"), 
    height = 6, width = 10)
upset_gene
```

## High dose
```{r}
# set var
thresh <- 0.1
myLfc <- 0.2

# paths
prefix <- paste0(out, model, "DEG_tables/")
suffix <- "_FDRq_1.00_LFC_0.00.tsv"

# read tables
high.8h <- read.delim(paste0(out, model, 
                            "DEG_tables/H.8h_vs_S.8h_FDRq_1.00_LFC_0.00.tsv"))
high.24h <- read.delim(paste0(out, model, 
                             "DEG_tables/H.24h_vs_S.24h_FDRq_1.00_LFC_0.00.tsv"))
high.7d <- read.delim(paste0(out, model, 
                            "DEG_tables/H.7d_vs_S.7d_FDRq_1.00_LFC_0.00.tsv"))
rownames(high.8h) <- high.8h$gene_name_unique
rownames(high.24h) <- high.24h$gene_name_unique
rownames(high.7d) <- high.7d$gene_name_unique

# filter on pval
high.8h <- high.8h[high.8h$adj.P.Val < thresh,]
high.24h <- high.24h[high.24h$adj.P.Val < thresh,]
high.7d <- high.7d[high.7d$adj.P.Val < thresh,]

# Subset lists
high.8h.up <- subset(high.8h$gene_name_unique, high.8h$logFC > myLfc)
high.8h.down <- subset(high.8h$gene_name_unique, high.8h$logFC < -myLfc)
high.24h.up <- subset(high.24h$gene_name_unique, high.24h$logFC > myLfc)
high.24h.down <- subset(high.24h$gene_name_unique, high.24h$logFC < -myLfc)
high.7d.up <- subset(high.7d$gene_name_unique, high.7d$logFC > myLfc)
high.7d.down <- subset(high.7d$gene_name_unique, high.7d$logFC < -myLfc)
list_input <- list("7 day High Dose Psilocybin vs Saline Up-regulated" = high.7d.up,
                   "24 hr High Dose Psilocybin vs Saline Up-regulated" = high.24h.up,
                   "8 hr High Dose Psilocybin vs Saline Up-regulated" = high.8h.up,
                   "7 day High Dose Psilocybin vs Saline Down-regulated" = high.7d.down,
                   "24 hr High Dose Psilocybin vs Saline Down-regulated" = high.24h.down,
                   "8 hr High Dose Psilocybin vs Saline Down-regulated" = high.8h.down)
data <- fromList(list_input)
  
# store names
names <- colnames(data)
  
# plot
upset_gene <- ComplexUpset::upset(data, 
				  names,
				  set_sizes=(
					upset_set_size()
					+ geom_text(aes(label=..count..), hjust=1.1, stat='count')
					+ expand_limits(y=750)),
				  queries = list(upset_query("8 hr High Dose Psilocybin vs Saline Up-regulated", fill = "red"),
								 upset_query("24 hr High Dose Psilocybin vs Saline Up-regulated", fill = "red"),
								 upset_query("7 day High Dose Psilocybin vs Saline Up-regulated", fill = "red"),
								 upset_query("8 hr High Dose Psilocybin vs Saline Down-regulated", fill = "blue"),
								 upset_query("24 hr High Dose Psilocybin vs Saline Down-regulated", fill = "blue"),
								 upset_query("7 day High Dose Psilocybin vs Saline Down-regulated", fill = "blue")),
				  base_annotations = list('Intersection size' = (
					intersection_size(bar_number_threshold=1, width=0.5)
					+ scale_y_continuous(expand=expansion(mult=c(0, 0.05)),limits = c(0,750)) # space on top
					+ theme(
						  # hide grid lines
						  panel.grid.major=element_blank(),
						  panel.grid.minor=element_blank(),
						  # show axis lines
						  axis.line=element_line(colour='black')))),
				  stripes = upset_stripes(
					geom=geom_segment(size=12),  # make the stripes larger
					colors=c('grey95', 'white')),
				  # to prevent connectors from getting the colorured
				  # use `fill` instead of `color`, together with `shape='circle filled'`
				  matrix = intersection_matrix(
					geom=geom_point(
					  shape='circle filled',
					  size=3,
					  stroke=0.45)),
				  sort_sets=FALSE,
				  sort_intersections='descending'
				)

upset_gene <- upset_gene + ggtitle(paste0("H Comparison, FDRq < ", format(thresh, nsmall = 2),
                                          ", |LFC| > ", format(myLfc, nsmall = 2)))

# save
pdf(paste0(out, model, "/upset/H_comparison_FDRq_", format(thresh, nsmall = 2), 
           "_LFC_", format(myLfc, nsmall = 2), ".pdf"), 
    height = 6, width = 10)
upset_gene
```

## 8 hours
```{r}
# set var
thresh <- 0.1
myLfc <- 0.2

# paths
prefix <- paste0(out, model, "DEG_tables/")
suffix <- "_FDRq_1.00_LFC_0.00.tsv"

# read tables
l.8h <- read.delim(paste0(out, model, "DEG_tables/L.8h_vs_S.8h_FDRq_1.00_LFC_0.00.tsv"))
h.8h <- read.delim(paste0(out, model, "DEG_tables/H.8h_vs_S.8h_FDRq_1.00_LFC_0.00.tsv"))
rownames(l.8h) <- l.8h$gene_name_unique
rownames(h.8h) <- h.8h$gene_name_unique

# filter on pval
l.8h <- l.8h[l.8h$adj.P.Val < thresh,]
h.8h <- h.8h[h.8h$adj.P.Val < thresh,]

# Subset lists
l.8h.up <- subset(l.8h$gene_name_unique, l.8h$logFC > myLfc)
l.8h.down <- subset(l.8h$gene_name_unique, l.8h$logFC < -myLfc)
h.8h.up <- subset(h.8h$gene_name_unique, h.8h$logFC > myLfc)
h.8h.down <- subset(h.8h$gene_name_unique, h.8h$logFC < -myLfc)
list_input <- list("8 hr High Psilocybin vs Saline Up-regulated" = h.8h.up,
                   "8 hr Low Psilocybin vs Saline Up-regulated" = l.8h.up,
                   "8 hr High Psilocybin vs Saline Down-regulated" = h.8h.down,
                   "8 hr Low Psilocybin vs Saline Down-regulated" = l.8h.down)
data <- fromList(list_input)
  
# store names
names <- colnames(data)
  
# plot
upset_gene <- ComplexUpset::upset(data, 
				  names,
				  set_sizes=(
					upset_set_size()
					+ geom_text(aes(label=..count..), hjust=1.1, stat='count')
					+ expand_limits(y=50)),
				  queries = list(
				    upset_query("8 hr High Psilocybin vs Saline Up-regulated", fill = "red"),
				    upset_query("8 hr Low Psilocybin vs Saline Up-regulated", fill = "red"),
				    upset_query("8 hr High Psilocybin vs Saline Down-regulated", fill = "blue"),
				    upset_query("8 hr Low Psilocybin vs Saline Down-regulated", fill = "blue")),
				  base_annotations = list('Intersection size' = (
					intersection_size(bar_number_threshold=1, width=0.5)
					+ scale_y_continuous(expand=expansion(mult=c(0, 0.05)),limits = c(0,50)) # space on top
					+ theme(
						  # hide grid lines
						  panel.grid.major=element_blank(),
						  panel.grid.minor=element_blank(),
						  # show axis lines
						  axis.line=element_line(colour='black')))),
				  stripes = upset_stripes(
					geom=geom_segment(size=12),  # make the stripes larger
					colors=c('grey95', 'white')),
				  # to prevent connectors from getting the colorured
				  # use `fill` instead of `color`, together with `shape='circle filled'`
				  matrix = intersection_matrix(
					geom=geom_point(
					  shape='circle filled',
					  size=3,
					  stroke=0.45)),
				  sort_sets=FALSE,
				  sort_intersections='descending'
				)

upset_gene <- upset_gene + ggtitle(paste0("8 Hours, FDRq < ", format(thresh, nsmall = 2),
                                          ", |LFC| > ", format(myLfc, nsmall = 2)))

# save
pdf(paste0(out, model, "/upset/8_hour_comparison_FDRq_", format(thresh, nsmall = 2), 
           "_LFC_", format(myLfc, nsmall = 2), ".pdf"), 
    height = 6, width = 15)
upset_gene
```

## 24 hours
```{r}
# set var
thresh <- 0.1
myLfc <- 0.2

# paths
prefix <- paste0(out, model, "DEG_tables/")
suffix <- "_FDRq_1.00.tsv"

# read tables
l.24h <- read.delim(paste0(out, model, "DEG_tables/L.24h_vs_S.24h_FDRq_1.00_LFC_0.00.tsv"))
h.24h <- read.delim(paste0(out, model, "DEG_tables/H.24h_vs_S.24h_FDRq_1.00_LFC_0.00.tsv"))
rownames(l.24h) <- l.24h$gene_name_unique
rownames(h.24h) <- h.24h$gene_name_unique

# filter on pval
l.24h <- l.24h[l.24h$adj.P.Val < thresh,]
h.24h <- h.24h[h.24h$adj.P.Val < thresh,]

# Subset lists
l.24h.up <- subset(l.24h$gene_name_unique, l.24h$logFC > myLfc)
l.24h.down <- subset(l.24h$gene_name_unique, l.24h$logFC < -myLfc)
h.24h.up <- subset(h.24h$gene_name_unique, h.24h$logFC > myLfc)
h.24h.down <- subset(h.24h$gene_name_unique, h.24h$logFC < -myLfc)
list_input <- list("24 hr High Psilocybin vs Saline Up-regulated" = h.24h.up,
                   "24 hr Low Psilocybin vs Saline Up-regulated" = l.24h.up,
                   "24 hr High Psilocybin vs Saline Down-regulated" = h.24h.down,
                   "24 hr Low Psilocybin vs Saline Down-regulated" = l.24h.down)
data <- fromList(list_input)
  
# store names
names <- colnames(data)
  
# plot
upset_gene <- ComplexUpset::upset(data, 
				  names,
				  set_sizes=(
					upset_set_size()
					+ geom_text(aes(label=..count..), hjust=1.1, stat='count')
					+ expand_limits(y=750)),
				  queries = list(
				    upset_query("24 hr High Psilocybin vs Saline Up-regulated", fill = "red"),
				    upset_query("24 hr Low Psilocybin vs Saline Up-regulated", fill = "red"),
						upset_query("24 hr High Psilocybin vs Saline Down-regulated", fill = "blue"),
				    upset_query("24 hr Low Psilocybin vs Saline Down-regulated", fill = "blue")),
				  base_annotations = list('Intersection size' = (
					intersection_size(bar_number_threshold=1, width=0.5)
					+ scale_y_continuous(expand=expansion(mult=c(0, 0.05)),limits = c(0,750)) # space on top
					+ theme(
						  # hide grid lines
						  panel.grid.major=element_blank(),
						  panel.grid.minor=element_blank(),
						  # show axis lines
						  axis.line=element_line(colour='black')))),
				  stripes = upset_stripes(
					geom=geom_segment(size=12),  # make the stripes larger
					colors=c('grey95', 'white')),
				  # to prevent connectors from getting the colorured
				  # use `fill` instead of `color`, together with `shape='circle filled'`
				  matrix = intersection_matrix(
					geom=geom_point(
					  shape='circle filled',
					  size=3,
					  stroke=0.45)),
				  sort_sets=FALSE,
				  sort_intersections='descending'
				)

upset_gene <- upset_gene + ggtitle(paste0("24 Hours, FDRq < ", format(thresh, nsmall = 2),
                                          ", |LFC| > ", format(myLfc, nsmall = 2)))

# save
pdf(paste0(out, model, "/upset/24_hour_comparison_FDRq_", format(thresh, nsmall = 2), 
           "_LFC_", format(myLfc, nsmall = 2), ".pdf"), 
    height = 6, width = 16)
upset_gene
```

## 7 days
```{r}
# set var
thresh <- 0.1
myLfc <- 0.2

# paths
prefix <- paste0(out, model, "DEG_tables/")
suffix <- "_FDRq_1.00.tsv"

# read tables
l.7d <- read.delim(paste0(out, model, "DEG_tables/L.7d_vs_S.7d_FDRq_1.00_LFC_0.00.tsv"))
h.7d <- read.delim(paste0(out, model, "DEG_tables/H.7d_vs_S.7d_FDRq_1.00_LFC_0.00.tsv"))
rownames(l.7d) <- l.7d$gene_name_unique
rownames(h.7d) <- h.7d$gene_name_unique

# filter on pval
l.7d <- l.7d[l.7d$adj.P.Val < thresh,]
h.7d <- h.7d[h.7d$adj.P.Val < thresh,]

# Subset lists
l.7d.up <- subset(l.7d$gene_name_unique, l.7d$logFC > myLfc)
l.7d.down <- subset(l.7d$gene_name_unique, l.7d$logFC < -myLfc)
h.7d.up <- subset(h.7d$gene_name_unique, h.7d$logFC > myLfc)
h.7d.down <- subset(h.7d$gene_name_unique, h.7d$logFC < -myLfc)
list_input <- list("7 days High Psilocybin vs Saline Up-regulated" = h.7d.up,
                   "7 days Low Psilocybin vs Saline Up-regulated" = l.7d.up,
                   "7 days High Psilocybin vs Saline Down-regulated" = h.7d.down,
                   "7 days Low Psilocybin vs Saline Down-regulated" = l.7d.down)
data <- fromList(list_input)
  
# store names
names <- colnames(data)
  
# plot
upset_gene <- ComplexUpset::upset(data, 
				  names,
				  set_sizes=(
					upset_set_size()
					+ geom_text(aes(label=..count..), hjust=1.1, stat='count')
					+ expand_limits(y=200)),
				  queries = list(
				    upset_query("7 days High Psilocybin vs Saline Up-regulated", fill = "red"),
				    upset_query("7 days Low Psilocybin vs Saline Up-regulated", fill = "red"),
						upset_query("7 days High Psilocybin vs Saline Down-regulated", fill = "blue"),
				    upset_query("7 days Low Psilocybin vs Saline Down-regulated", fill = "blue")),
				  base_annotations = list('Intersection size' = (
					intersection_size(bar_number_threshold=1, width=0.5)
					+ scale_y_continuous(expand=expansion(mult=c(0, 0.05)),limits = c(0,200)) # space on top
					+ theme(
						  # hide grid lines
						  panel.grid.major=element_blank(),
						  panel.grid.minor=element_blank(),
						  # show axis lines
						  axis.line=element_line(colour='black')))),
				  stripes = upset_stripes(
					geom=geom_segment(size=12),  # make the stripes larger
					colors=c('grey95', 'white')),
				  # to prevent connectors from getting the colorured
				  # use `fill` instead of `color`, together with `shape='circle filled'`
				  matrix = intersection_matrix(
					geom=geom_point(
					  shape='circle filled',
					  size=3,
					  stroke=0.45)),
				  sort_sets=FALSE,
				  sort_intersections='descending'
				)

upset_gene <- upset_gene + ggtitle(paste0("FDRq < ", format(thresh, nsmall = 2),
                                          ", |LFC| > ", format(myLfc, nsmall = 2)))

# save
pdf(paste0(out, model, "/upset/7_day_comparison_FDRq_", format(thresh, nsmall = 2), 
           "_LFC_", format(myLfc, nsmall = 2), ".pdf"), 
    height = 6, width = 16)
upset_gene
```

# Upset: all_samples vs all_samples_combat
## 7 days low
```{r}
# set var
thresh <- 0.1
myLfc <- 0.2

# read tables
nc.l.7d <- read.delim(paste0("../../results/all_samples/DEGs_with_hbb/",
                            "both_sexes/DEG_tables/L.7d_vs_S.7d_FDRq_1.00_LFC_0.00.tsv"))
c.l.7d <- read.delim(paste0("../../results/all_samples_combat/DEGs_with_hbb/",
                            "both_sexes/DEG_tables/L.7d_vs_S.7d_FDRq_1.00_LFC_0.00.tsv"))
rownames(nc.l.7d) <- nc.l.7d$gene_name_unique
rownames(c.l.7d) <- c.l.7d$gene_name_unique

# filter on pval
nc.l.7d <- nc.l.7d[nc.l.7d$adj.P.Val < thresh,]
c.l.7d <- c.l.7d[c.l.7d$adj.P.Val < thresh,]

# Subset lists
nc.l.7d.up <- subset(nc.l.7d$gene_name_unique, nc.l.7d$logFC > myLfc)
nc.l.7d.down <- subset(nc.l.7d$gene_name_unique, nc.l.7d$logFC < -myLfc)
c.l.7d.up <- subset(c.l.7d$gene_name_unique, c.l.7d$logFC > myLfc)
c.l.7d.down <- subset(c.l.7d$gene_name_unique, c.l.7d$logFC < -myLfc)
list_input <- list("ComBat, 7 Days, Low Psilocybin vs Saline, Up-regulated" = c.l.7d.up,
                   "Non-ComBat, 7 Days, Low Psilocybin vs Saline, Up-regulated" = nc.l.7d.up,
                   "ComBat, 7 Days, Low Psilocybin vs Saline, Down-regulated" = c.l.7d.down,
                   "Non-ComBat, 7 Days, Low Psilocybin vs Saline, Down-regulated" = nc.l.7d.down)
data <- fromList(list_input)
  
# store names
names <- colnames(data)
  
# plot
upset_gene <- ComplexUpset::upset(data, 
				  names,
				  set_sizes=(
					upset_set_size()
					+ geom_text(aes(label=..count..), hjust=1.1, stat='count')
					+ expand_limits(y=150)),
				  queries = list(
				    upset_query("ComBat, 7 Days, Low Psilocybin vs Saline, Up-regulated", fill = "red"),
				    upset_query("Non-ComBat, 7 Days, Low Psilocybin vs Saline, Up-regulated", fill = "red"),
						upset_query("ComBat, 7 Days, Low Psilocybin vs Saline, Down-regulated", fill = "blue"),
				    upset_query("Non-ComBat, 7 Days, Low Psilocybin vs Saline, Down-regulated", fill = "blue")),
				  base_annotations = list('Intersection size' = (
					intersection_size(bar_number_threshold=1, width=0.5)
					+ scale_y_continuous(expand=expansion(mult=c(0, 0.05)),limits = c(0,100)) # space on top
					+ theme(
						  # hide grid lines
						  panel.grid.major=element_blank(),
						  panel.grid.minor=element_blank(),
						  # show axis lines
						  axis.line=element_line(colour='black')))),
				  stripes = upset_stripes(
					geom=geom_segment(size=12),  # make the stripes larger
					colors=c('grey95', 'white')),
				  # to prevent connectors from getting the colorured
				  # use `fill` instead of `color`, together with `shape='circle filled'`
				  matrix = intersection_matrix(
					geom=geom_point(
					  shape='circle filled',
					  size=3,
					  stroke=0.45)),
				  sort_sets=FALSE,
				  sort_intersections='descending'
				)

upset_gene <- upset_gene + ggtitle(paste0("FDRq < ", format(thresh, nsmall = 2),
                                          ", |LFC| > ", format(myLfc, nsmall = 2)))

# save
pdf(paste0("../../results/compare_analyses/7_day_low_dose_comparison_FDRq_", format(thresh, nsmall = 2), 
           "_LFC_", format(myLfc, nsmall = 2), ".pdf"), 
    height = 6, width = 16)
upset_gene
```

## 24 hours high dose
```{r}
# set var
thresh <- 0.05
myLfc <- 0

# read tables
nc.h.24h <- read.delim(paste0("../../results/all_samples/DEGs_with_hbb/",
                            "both_sexes/DEG_tables/H.24h_vs_S.24h_FDRq_1.00_LFC_0.00.tsv"))
c.h.24h <- read.delim(paste0("../../results/all_samples_combat/DEGs_with_hbb/",
                            "both_sexes/DEG_tables/H.24h_vs_S.24h_FDRq_1.00_LFC_0.00.tsv"))
rownames(nc.h.24h) <- nc.h.24h$gene_name_unique
rownames(c.h.24h) <- c.h.24h$gene_name_unique

# filter on pval
nc.h.24h <- nc.h.24h[nc.h.24h$adj.P.Val < thresh,]
c.h.24h <- c.h.24h[c.h.24h$adj.P.Val < thresh,]

# Subset lists
nc.h.24h.up <- subset(nc.h.24h$gene_name_unique, nc.h.24h$logFC > myLfc)
nc.h.24h.down <- subset(nc.h.24h$gene_name_unique, nc.h.24h$logFC < -myLfc)
c.h.24h.up <- subset(c.h.24h$gene_name_unique, c.h.24h$logFC > myLfc)
c.h.24h.down <- subset(c.h.24h$gene_name_unique, c.h.24h$logFC < -myLfc)
list_input <- list("ComBat, 24 Hours, High Psilocybin vs Saline, Up-regulated" = c.h.24h.up,
                   "Non-ComBat, 24 Hours, High Psilocybin vs Saline, Up-regulated" = nc.h.24h.up,
                   "ComBat, 24 Hours, High Psilocybin vs Saline, Down-regulated" = c.h.24h.down,
                   "Non-ComBat, 24 Hours, High Psilocybin vs Saline, Down-regulated" = nc.h.24h.down)
data <- fromList(list_input)
  
# store names
names <- colnames(data)
  
# plot
upset_gene <- ComplexUpset::upset(data, 
				  names,
				  set_sizes=(
					upset_set_size()
					+ geom_text(aes(label=..count..), hjust=1.1, stat='count')
					+ expand_limits(y=2000)),
				  queries = list(
				    upset_query("ComBat, 24 Hours, High Psilocybin vs Saline, Up-regulated", fill = "red"),
				    upset_query("Non-ComBat, 24 Hours, High Psilocybin vs Saline, Up-regulated", fill = "red"),
						upset_query("ComBat, 24 Hours, High Psilocybin vs Saline, Down-regulated", fill = "blue"),
				    upset_query("Non-ComBat, 24 Hours, High Psilocybin vs Saline, Down-regulated", fill = "blue")),
				  base_annotations = list('Intersection size' = (
					intersection_size(bar_number_threshold=1, width=0.5)
					+ scale_y_continuous(expand=expansion(mult=c(0, 0.05)),limits = c(0,2000)) # space on top
					+ theme(
						  # hide grid lines
						  panel.grid.major=element_blank(),
						  panel.grid.minor=element_blank(),
						  # show axis lines
						  axis.line=element_line(colour='black')))),
				  stripes = upset_stripes(
					geom=geom_segment(size=12),  # make the stripes larger
					colors=c('grey95', 'white')),
				  # to prevent connectors from getting the colorured
				  # use `fill` instead of `color`, together with `shape='circle filled'`
				  matrix = intersection_matrix(
					geom=geom_point(
					  shape='circle filled',
					  size=3,
					  stroke=0.45)),
				  sort_sets=FALSE,
				  sort_intersections='descending'
				)

upset_gene <- upset_gene + ggtitle(paste0("FDRq < ", format(thresh, nsmall = 2),
                                          ", |LFC| > ", format(myLfc, nsmall = 2)))

# save
pdf(paste0("../../results/compare_analyses/24_hours_high_dose_comparison_FDRq_", format(thresh, nsmall = 2), 
           "_LFC_", format(myLfc, nsmall = 2), ".pdf"), 
    height = 6, width = 16)
upset_gene
```
# 3D LogFC Correaltion
## Low dose
```{r low_dose_3D}
# read tables
low.8h <- read.delim(paste0(out, model, "DEG_tables/psilo.low.8h_vs_sal.8h_FDRq_1.00.tsv"))
low.24h <- read.delim(paste0(out, model, "DEG_tables/psilo.low.24h_vs_sal.24h_FDRq_1.00.tsv"))
low.7d <- read.delim(paste0(out, model, "DEG_tables/psilo.low.7d_vs_sal.7d_FDRq_1.00.tsv"))

# extract logFC
df <- data.frame(genes = low.8h$gene_name_unique,
                 low.8h = low.8h$logFC,
                 low.24h = low.24h$logFC,
                 low.7d = low.7d$logFC)
rownames(df) <- df$genes

# direction, 1 = upreg, 2 = downreg, 3 = other
df$direction <- ""
for (gene in df$genes) {
  if((df[gene,"low.8h"] > 0) && (df[gene,"low.24h"] > 0) && (df[gene,"low.7d"] > 0)) {
    df[gene, "direction"] <- "up-up-up"
  } else if ((df[gene,"low.8h"] < 0) && (df[gene,"low.24h"] < 0) && (df[gene,"low.7d"] < 0)) {
    df[gene, "direction"] <- "down-down-down"
  } else if((df[gene,"low.8h"] < 0) && (df[gene,"low.24h"] < 0) && (df[gene,"low.7d"] > 0)) {
    df[gene, "direction"] <- "down-down-up"
  } else if((df[gene,"low.8h"] > 0) && (df[gene,"low.24h"] > 0) && (df[gene,"low.7d"] < 0)) {
    df[gene, "direction"] <- "up-up-down"
  } else if((df[gene,"low.8h"] < 0) && (df[gene,"low.24h"] > 0) && (df[gene,"low.7d"] < 0)) {
    df[gene, "direction"] <- "down-up-down"
  } else if((df[gene,"low.8h"] < 0) && (df[gene,"low.24h"] > 0) && (df[gene,"low.7d"] > 0)) {
    df[gene, "direction"] <- "down-up-up"
  } else if((df[gene,"low.8h"] < 0) && (df[gene,"low.24h"] < 0) && (df[gene,"low.7d"] > 0)) {
    df[gene, "direction"] <- "down-down-up"
  } else if((df[gene,"low.8h"] < 0) && (df[gene,"low.24h"] < 0) && (df[gene,"low.7d"] > 0)) {
    df[gene, "direction"] <- "down-down-up"
  } else if((df[gene,"low.8h"] > 0) && (df[gene,"low.24h"] < 0) && (df[gene,"low.7d"] > 0)) {
    df[gene, "direction"] <- "up-down-up"
  } else if((df[gene,"low.8h"] > 0) && (df[gene,"low.24h"] < 0) && (df[gene,"low.7d"] < 0)) {
    df[gene, "direction"] <- "up-down-down"
  } else {
    df[gene, "direction"] <- "other"
  }
}
df$direction <- factor(df$direction)

# plot
fig1 <- plot_ly(df, 
                x = ~low.8h, 
                y = ~low.24h, 
                z = ~low.7d, 
                color = ~direction, 
                colors = c("blue","purple","yellow","orange","green",
                                 "gray","pink","red"),
                text = ~genes) %>%
  add_markers() %>% 
  layout(legend=list(title=list(text='<b> Low: 8h vs 24h vs 7d </b>')))
fig1
```

## High dose
```{r high_dose_3D}
# read tables
high.8h <- read.delim(paste0(out, model, "DEG_tables/psilo.high.8h_vs_sal.8h_FDRq_1.00.tsv"))
high.24h <- read.delim(paste0(out, model, "DEG_tables/psilo.high.24h_vs_sal.24h_FDRq_1.00.tsv"))
high.7d <- read.delim(paste0(out, model, "DEG_tables/psilo.high.7d_vs_sal.7d_FDRq_1.00.tsv"))

# extract logFC
df <- data.frame(genes = high.8h$gene_name_unique,
                 high.8h = high.8h$logFC,
                 high.24h = high.24h$logFC,
                 high.7d = high.7d$logFC)
rownames(df) <- df$genes

# direction, 1 = upreg, 2 = downreg, 3 = other
df$direction <- ""
for (gene in df$genes) {
  if((df[gene,"high.8h"] > 0) && (df[gene,"high.24h"] > 0) && (df[gene,"high.7d"] > 0)) {
    df[gene, "direction"] <- "up-up-up"
  } else if ((df[gene,"high.8h"] < 0) && (df[gene,"high.24h"] < 0) && (df[gene,"high.7d"] < 0)) {
    df[gene, "direction"] <- "down-down-down"
  } else if((df[gene,"high.8h"] < 0) && (df[gene,"high.24h"] < 0) && (df[gene,"high.7d"] > 0)) {
    df[gene, "direction"] <- "down-down-up"
  } else if((df[gene,"high.8h"] > 0) && (df[gene,"high.24h"] > 0) && (df[gene,"high.7d"] < 0)) {
    df[gene, "direction"] <- "up-up-down"
  } else if((df[gene,"high.8h"] < 0) && (df[gene,"high.24h"] > 0) && (df[gene,"high.7d"] < 0)) {
    df[gene, "direction"] <- "down-up-down"
  } else if((df[gene,"high.8h"] < 0) && (df[gene,"high.24h"] > 0) && (df[gene,"high.7d"] > 0)) {
    df[gene, "direction"] <- "down-up-up"
  } else if((df[gene,"high.8h"] < 0) && (df[gene,"high.24h"] < 0) && (df[gene,"high.7d"] > 0)) {
    df[gene, "direction"] <- "down-down-up"
  } else if((df[gene,"high.8h"] < 0) && (df[gene,"high.24h"] < 0) && (df[gene,"high.7d"] > 0)) {
    df[gene, "direction"] <- "down-down-up"
  } else if((df[gene,"high.8h"] > 0) && (df[gene,"high.24h"] < 0) && (df[gene,"high.7d"] > 0)) {
    df[gene, "direction"] <- "up-down-up"
  } else if((df[gene,"high.8h"] > 0) && (df[gene,"high.24h"] < 0) && (df[gene,"high.7d"] < 0)) {
    df[gene, "direction"] <- "up-down-down"
  } else {
    df[gene, "direction"] <- "other"
  }
}
df$direction <- factor(df$direction)

# plot
fig2 <- plot_ly(df, 
                x = ~high.8h, 
                y = ~high.24h, 
                z = ~high.7d, 
                color = ~direction, 
                colors = c("blue","purple","yellow","orange","green",
                                 "gray","pink","red"),
                text = ~genes) %>%
  add_markers() %>% 
  layout(legend=list(title=list(text='<b> High: 8h vs 24h vs 7d </b>')))
fig2
```

# Line graph
## Low dose
```{r low_dose_line}
# read tables
low.8h <- read.delim(paste0(out, model, "DEG_tables/psilo.low.8h_vs_sal.8h_FDRq_1.00.tsv"))
low.24h <- read.delim(paste0(out, model, "DEG_tables/psilo.low.24h_vs_sal.24h_FDRq_1.00.tsv"))
low.7d <- read.delim(paste0(out, model, "DEG_tables/psilo.low.7d_vs_sal.7d_FDRq_1.00.tsv"))

# extract logFC
df <- data.frame(genes = low.8h$gene_name_unique,
                 low.8h = low.8h$logFC,
                 low.24h = low.24h$logFC,
                 low.7d = low.7d$logFC)
rownames(df) <- df$genes

# find absolute diff
df$diff_8h_vs_24h <- abs(df$low.8h - df$low.24h)
df$diff_24h_vs_7d <- abs(df$low.24h - df$low.7d)
df <- df[df$diff_24h_vs_7d > 0.2,]
df <- df[df$diff_8h_vs_24h > 0.2,]

# direction, 1 = upreg, 2 = downreg, 3 = other
df$direction <- ""
for (gene in df$genes) {
  if((df[gene,"low.8h"] > 0) && (df[gene,"low.24h"] > 0) && (df[gene,"low.7d"] > 0)) {
    df[gene, "direction"] <- "up-up-up"
  } else if ((df[gene,"low.8h"] < 0) && (df[gene,"low.24h"] < 0) && (df[gene,"low.7d"] < 0)) {
    df[gene, "direction"] <- "down-down-down"
  } else if((df[gene,"low.8h"] < 0) && (df[gene,"low.24h"] < 0) && (df[gene,"low.7d"] > 0)) {
    df[gene, "direction"] <- "down-down-up"
  } else if((df[gene,"low.8h"] > 0) && (df[gene,"low.24h"] > 0) && (df[gene,"low.7d"] < 0)) {
    df[gene, "direction"] <- "up-up-down"
  } else if((df[gene,"low.8h"] < 0) && (df[gene,"low.24h"] > 0) && (df[gene,"low.7d"] < 0)) {
    df[gene, "direction"] <- "down-up-down"
  } else if((df[gene,"low.8h"] < 0) && (df[gene,"low.24h"] > 0) && (df[gene,"low.7d"] > 0)) {
    df[gene, "direction"] <- "down-up-up"
  } else if((df[gene,"low.8h"] < 0) && (df[gene,"low.24h"] < 0) && (df[gene,"low.7d"] > 0)) {
    df[gene, "direction"] <- "down-down-up"
  } else if((df[gene,"low.8h"] < 0) && (df[gene,"low.24h"] < 0) && (df[gene,"low.7d"] > 0)) {
    df[gene, "direction"] <- "down-down-up"
  } else if((df[gene,"low.8h"] > 0) && (df[gene,"low.24h"] < 0) && (df[gene,"low.7d"] > 0)) {
    df[gene, "direction"] <- "up-down-up"
  } else if((df[gene,"low.8h"] > 0) && (df[gene,"low.24h"] < 0) && (df[gene,"low.7d"] < 0)) {
    df[gene, "direction"] <- "up-down-down"
  } else {
    df[gene, "direction"] <- "other"
  }
}
df$direction <- factor(df$direction)

# reformat
df <- pivot_longer(data = df, cols = 2:4, names_to = "dose")
colnames(df)[6] <- "logFC"
df$dose <- factor(df$dose, levels = c("low.8h", "low.24h", "low.7d"))

# plot
fig3 <- plot_ly(df,
                x = ~dose,
                y = ~logFC,
                type = "scatter",
                mode = "lines",
                text = df$genes,
                color = ~direction,
                colors = c("blue","purple","yellow","orange","green",
                                 "gray","pink","red"))
fig3
```

## High dose
```{r high_dose_line}
# read tables
high.8h <- read.delim(paste0(out, model, "DEG_tables/psilo.high.8h_vs_sal.8h_FDRq_1.00.tsv"))
high.24h <- read.delim(paste0(out, model, "DEG_tables/psilo.high.24h_vs_sal.24h_FDRq_1.00.tsv"))
high.7d <- read.delim(paste0(out, model, "DEG_tables/psilo.high.7d_vs_sal.7d_FDRq_1.00.tsv"))

# extract logFC
df <- data.frame(genes = high.8h$gene_name_unique,
                 high.8h = high.8h$logFC,
                 high.24h = high.24h$logFC,
                 high.7d = high.7d$logFC)
rownames(df) <- df$genes

# find absolute diff
df$diff_8h_vs_24h <- abs(df$high.8h - df$high.24h)
df$diff_24h_vs_7d <- abs(df$high.24h - df$high.7d)
df <- df[df$diff_24h_vs_7d > 0.2,]
df <- df[df$diff_8h_vs_24h > 0.2,]

# direction, 1 = upreg, 2 = downreg, 3 = other
df$direction <- ""
for (gene in df$genes) {
  if((df[gene,"high.8h"] > 0) && (df[gene,"high.24h"] > 0) && (df[gene,"high.7d"] > 0)) {
    df[gene, "direction"] <- "up-up-up"
  } else if ((df[gene,"high.8h"] < 0) && (df[gene,"high.24h"] < 0) && (df[gene,"high.7d"] < 0)) {
    df[gene, "direction"] <- "down-down-down"
  } else if((df[gene,"high.8h"] < 0) && (df[gene,"high.24h"] < 0) && (df[gene,"high.7d"] > 0)) {
    df[gene, "direction"] <- "down-down-up"
  } else if((df[gene,"high.8h"] > 0) && (df[gene,"high.24h"] > 0) && (df[gene,"high.7d"] < 0)) {
    df[gene, "direction"] <- "up-up-down"
  } else if((df[gene,"high.8h"] < 0) && (df[gene,"high.24h"] > 0) && (df[gene,"high.7d"] < 0)) {
    df[gene, "direction"] <- "down-up-down"
  } else if((df[gene,"high.8h"] < 0) && (df[gene,"high.24h"] > 0) && (df[gene,"high.7d"] > 0)) {
    df[gene, "direction"] <- "down-up-up"
  } else if((df[gene,"high.8h"] < 0) && (df[gene,"high.24h"] < 0) && (df[gene,"high.7d"] > 0)) {
    df[gene, "direction"] <- "down-down-up"
  } else if((df[gene,"high.8h"] < 0) && (df[gene,"high.24h"] < 0) && (df[gene,"high.7d"] > 0)) {
    df[gene, "direction"] <- "down-down-up"
  } else if((df[gene,"high.8h"] > 0) && (df[gene,"high.24h"] < 0) && (df[gene,"high.7d"] > 0)) {
    df[gene, "direction"] <- "up-down-up"
  } else if((df[gene,"high.8h"] > 0) && (df[gene,"high.24h"] < 0) && (df[gene,"high.7d"] < 0)) {
    df[gene, "direction"] <- "up-down-down"
  } else {
    df[gene, "direction"] <- "other"
  }
}
df$direction <- factor(df$direction)

# reformat
df <- pivot_longer(data = df, cols = 2:4, names_to = "dose")
colnames(df)[6] <- "logFC"
df$dose <- factor(df$dose, levels = c("high.8h", "high.24h", "high.7d"))

# plot
fig4 <- plot_ly(df,
                x = ~dose,
                y = ~logFC,
                type = "scatter",
                mode = "lines",
                text = df$genes,
                color = ~direction,
                colors = c("blue","purple","yellow","orange","green",
                                 "gray","pink","red"))
fig4
```

